name: Container Image

on:
  push:
    branches:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  build-container:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
    - if: github.ref_type == 'branch'
      run: docker tag ${{ env.IMAGE_NAME }}:${{ github.ref_name }} ${{ env.IMAGE_NAME }}:${GITHUB_SHA:0:8}
    - if: github.ref_type == 'tag'
      run: docker tag ${{ env.IMAGE_NAME }}:${{ github.ref_name }} ${{ env.IMAGE_NAME }}:latest
    - run: docker push ${{ env.IMAGE_NAME }} --all-tags
