name: Docker Image CI

on:
  push:
    tags: v[0-9].[0-9].[0-9]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.ref_name }}
    
jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: docker build . --file Dockerfile --tag ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --tag ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:latest
    - run: docker push ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }} --all-tags
